### ISSUE TITLE
helm-cscope does not work when cscope db is created with absolute path.

### ISSUE THREAD

**Issue by casch-at** [alpha22jp/helm-cscope.el#5]
Hey,

I have just encountered an issue, when I search for a symbol using the function `helm-cscope-find-this-symbol` it can not open the file as I create usually the cscope db with absolute path.

After the result of the query is displayed in the `*Helm cscope*` buffer and I press enter on one of the results, the following warning is displayed in the minibuffer.

```
Setting current directory: no such file or directory, /home/cschwarzgruber/Developing/c/fx12_lcd/sdk_workspace/home/cschwarzgruber/Developing/c/fx12_lcd/sdk_workspace/SoC_Project/src/
```

Chris

**Comment by alpha22jp** [comment]
Hi, @cslux 
1. Does the problem happen every time you do the same operation, or just once?
2. Does the directory in your warning message actually exist?

**Comment by casch-at** [comment]
Hi, @alpha22jp 

> Does the problem happen every time you do the same operation, or just once?

Yes, this always happens.

> Does the directory in your warning message actually exist?

Sure, the only thing is that there is two times the same path prefix, that's why the file cannot be found. That is because I create the cscope db with absolute paths.

``` sh
/home/cschwarzgruber/Developing/fx12_lcd/sdk_workspace/
```

If I run the following commands to recreate the cscope db with relative paths.

``` sh
sed -i 's|/home/cschwarzgruber/Developing/fx12_lcd/sdk_workspace/'||g' cscope.file 
cscope -bq 
```

`helm-cscope-find-this-symbol` function works as supposed.

In short if the cscope db returns absolute paths, than no path should be concatenated to the path as the path is already absolute. Or even better remove the prefix path before displaying the result in the _Helm cscope_ buffer, so only the path relative to the cscope db is shown (the shorter the better :-).

**Comment by casch-at** [comment]
This patch fixes the problem for me (take it with caution, I have almost no lisp skills). The cscope db can now be created either with absolute or relative paths.

``` diff
diff --git a/helm-cscope.el b/helm-cscope.el
index c8316c6..bcb06ef 100644
--- a/helm-cscope.el
+++ b/helm-cscope.el
@@ -118,11 +118,11 @@

 (defun helm-cscope--open-file (dir line &optional persistent)
   (when (string-match helm-cscope--parse-regexp line)
-    (let ((file (concat dir (match-string 1 line)))
+    (let ((file (match-string 1 line))
           (line-number (string-to-number (match-string 3 line)))
           (text (match-string 4 line)))
       (unless persistent (ring-insert cscope-marker-ring (point-marker)))
-      (find-file file)
+      (find-file (if (file-name-absolute-p file) file (concat dir file)))
       (helm-cscope--goto-line text line-number)
       (if persistent (helm-highlight-current-line)))))
```

However, it would be nice if the path, in this case the value of `dir`, gets striped away before the search result will be displayed, as the value of `dir` will be displayed in the `*Helm buffer*` anyway.

Maybe I find it out my self, if I do, I will post the patch here.

**Comment by casch-at** [comment]
Patch number two. 
Display file name relative to the cscope db only.

``` diff
diff --git a/helm-cscope.el b/helm-cscope.el
index bcb06ef..868e35f 100644
--- a/helm-cscope.el
+++ b/helm-cscope.el
@@ -131,20 +131,23 @@
    (lambda (e) (string-match helm-cscope--parse-regexp (cdr e)))
    candidates))

-(defun helm-cscope--transform (line)
+(defun helm-cscope--transform (dir line)
   (when (string-match helm-cscope--parse-regexp line)
-    (format "%s: %s(%s) %s"
-            (propertize (match-string 1 line) 'face 'helm-cscope-file-face)
-            (propertize (match-string 2 line) 'face 'helm-cscope-function-face)
-            (propertize (match-string 3 line) 'face 'helm-cscope-lineno-face)
-            (match-string 4 line))))
+    (let ((file (match-string 1 line)))
+      (format "%s: %s(%s) %s"
+              (propertize (if (file-name-absolute-p file)
+                              (replace-regexp-in-string dir "" file)
+                            file) 'face 'helm-cscope-file-face)
+              (propertize (match-string 2 line) 'face 'helm-cscope-function-face)
+              (propertize (match-string 3 line) 'face 'helm-cscope-lineno-face)
+              (match-string 4 line)))))

 (defun helm-cscope--make-source (dir db-name search-type-arg search-text args)
   (helm-build-in-buffer-source dir
     :init (lambda () (helm-cscope--search
                       dir db-name search-type-arg search-text args))
     :filtered-candidate-transformer 'helm-cscope--filter-candidates
-    :real-to-display 'helm-cscope--transform
+    :real-to-display (lambda (line) (helm-cscope--transform dir line))
     :fuzzy-match t
     :action (lambda (line) (helm-cscope--open-file dir line))
     :persistent-action (lambda (line) (helm-cscope--open-file dir line t))))
```

I have tested it with a cscope db with relative paths as well as absolute paths.
